import StartCard from "@/components/Home/StartCard";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import Head from "next/head";

export default function Home() {
  return (
    <div className="w-full h-full flex items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-2 w-[90vw] p-10">
        <StartCard />
      </div>
    </div>
  );
}

export const getServerSideProps = withPageAuthRequired();
